name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (o Python, o cualquier otro entorno)
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Versión que estás usando

    - name: Install dependencies
      run: npm install # o pip install, etc.

    - name: Run tests
      run: npm test # o pytest, etc.

    - name: Build application
      run: npm run build # o cualquier comando de compilación que utilices
